### ISSUE TITLE
What do you think about the mind map idea?

### ISSUE THREAD

**Issue by Binlogo** [zntfdr/WWDC-Notes#39]
I built a repo - [WWDC20-Track](https://github.com/Binlogo/WWDC20-Track) to track my WWDC watching notes, I like to use the mind map to make notes, so I share my mind map notes. Today, I find your awesome notes repo here, you did the great job. And I'm wondering what do you guys think about the mind map notes idea. If you think this idea is acceptable, I'd like to contribute parts of WWDC mind map notes, learning by sharing.😜 @zntfdr 

For example:

![What's New in Swift mind map](https://github.com/Binlogo/WWDC20-Track/blob/master/MindMaps/What'sNewinSwift.png?raw=true)

**Comment by dasautoooo** [comment]
Hi @Binlogo 👋. It's a cool project and your mindmaps are great! 

Mindmaps are great to structure knowledge, it's like a skinny note but well-curated.

If the mindmaps are images, it can be easily attached to the existing note without further feature development. However, I don't feel such a long large image will be viewed fluently on every device, it might add a little difficulty to the device like mobile. If the mindmap suggestion gets approved, I recommend adding the functionality to the website instead of attaching an image.

I like the mindmap idea. I was talking to Federico about adding a content list but I think mindmaps are better 😁.

What do you think @zntfdr ?

**Comment by zntfdr** [comment]
Hi @Binlogo, thanks for the kind words ❤️ 

Your mind map notes are notes written in a different format:  
with the example above, I see that you could turn the four main branches `Swift in Apple's OS and APIs`, `Language`, `Library`, `Cross-Platform` into chapters and the the rest into lists or sub-chapters.

As @dasautoooo says, the website has been built to support markdown notes and all device sizes, if you're ok with turning these mind notes into markdown notes, then that would be awesome!

**Comment by Binlogo** [comment]
Hi, @zntfdr , @dasautoooo .

Thanks for your replies. I know our notes use markdown, then generate website content. And the image content is not searchable. Attach image is not my intention, it's just a showcase, the [source content](https://mubu.com/doc/41BTbnA2hAo#mindmap) is searchable and interactive, but third-tool dependent.

I want to share the mind map idea it self, nor it generate from markdown or use some other tool build, it could be more structured (or maybe [Roam](https://roamresearch.com/) - support, is cool, too). I know it requires a lot of efforts, just ideas here. 

By the way, I'd accept your suggestions, try to do some markdown contribution. 😜

**Comment by zntfdr** [comment]
Hi @Binlogo, that's fantastic, thank you so much! 😊 

When writing my own notes I try to be as succinct as possible: 
your mind notes work great from this point of view 👍 

Looking forward to your PRs 😃
